# Generated by Django 2.2 on 2020-08-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200810_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '短信验证码', 'verbose_name_plural': '短信验证码'},
        ),
    ]
