# Generated by Django 2.2 on 2020-08-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200811_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifycode',
            old_name='mobile',
            new_name='tel',
        ),
    ]
