# Generated by Django 2.2 on 2020-08-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collect_num',
            field=models.IntegerField(default=0, help_text='已收藏文档数', verbose_name='已收藏文档数'),
        ),
    ]
