# Generated by Django 2.2 on 2020-08-17 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('role', models.IntegerField(default=0, verbose_name='0协作者1管理者')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document', verbose_name='文集')),
            ],
            options={
                'verbose_name': '文集协作',
            },
        ),
    ]
