# Generated by Django 2.2 on 2020-08-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='role',
        ),
    ]
