# Generated by Django 3.0.8 on 2020-08-10 14:52

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='评论内容', verbose_name='评论内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='发表时间', verbose_name='发表时间')),
                ('create_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='创建评论者')),
                ('dec', models.ForeignKey(default=1, help_text='被评论文档', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='docs.Doc', verbose_name='文档')),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
    ]
