# Generated by Django 2.2 on 2020-08-11 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0001_initial'),
        ('comments', '0003_auto_20200810_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='用户收藏时间', verbose_name='收藏时间')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collect', to=settings.AUTH_USER_MODEL, verbose_name='收藏者')),
                ('dec', models.ForeignKey(default=1, help_text='被收藏文档', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='docs.Doc', verbose_name='文档')),
            ],
            options={
                'ordering': ['-create_time'],
                'unique_together': {('author', 'dec')},
            },
        ),
    ]
