# Generated by Django 2.2 on 2020-08-14 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_auto_20200813_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='消息发送时间')),
                ('type', models.IntegerField(default=0, verbose_name='消息类型')),
                ('status', models.IntegerField(default=0, verbose_name='文档状态')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document', verbose_name='消息关联的文档/团队')),
                ('origin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to=settings.AUTH_USER_MODEL, verbose_name='消息发送人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to=settings.AUTH_USER_MODEL, verbose_name='消息接收者')),
            ],
            options={
                'verbose_name': '消息',
            },
        ),
    ]
