# Generated by Django 2.2 on 2020-08-10 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='文档标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文档内容')),
                ('parent_doc', models.IntegerField(default=0, verbose_name='上级文档')),
                ('top_doc', models.IntegerField(default=0, verbose_name='所属项目')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='文档创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='文档修改时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文档创建者')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
            },
        ),
    ]
