# Generated by Django 2.2 on 2020-08-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20200810_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='parent_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_docs', to='docs.Doc', verbose_name='上级文档'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='top_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_docs', to='projects.Project', verbose_name='所属项目'),
        ),
    ]
