# Generated by Django 2.2 on 2020-08-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20200810_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='status',
            field=models.IntegerField(default=1, verbose_name='文档状态'),
        ),
    ]
