# Generated by Django 2.2 on 2020-08-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_doc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='type',
            field=models.IntegerField(default=0, verbose_name='是否目录'),
        ),
    ]
