# Generated by Django 2.2 on 2020-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='role',
            field=models.IntegerField(default=1, verbose_name='权限等级'),
        ),
    ]
