# Generated by Django 2.2 on 2020-08-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='是否文件夹'),
        ),
    ]
