# Generated by Django 2.2 on 2020-08-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200815_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='create_by_model',
            field=models.ForeignKey(blank=True, help_text='模板', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='documents.Document', verbose_name='文档模板'),
        ),
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='缩略图', null=True, upload_to='upload', verbose_name='缩略图'),
        ),
    ]
