# Generated by Django 2.2 on 2020-08-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200811_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.IntegerField(default=0, verbose_name='是否文件夹'),
        ),
    ]
