# Generated by Django 2.2 on 2020-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20200811_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='top_doc',
        ),
        migrations.AlterField(
            model_name='document',
            name='role',
            field=models.IntegerField(default=0, verbose_name='0公开1私密'),
        ),
    ]
