# Generated by Django 2.2 on 2020-08-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200812_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='role',
            field=models.IntegerField(default=1, verbose_name='0公开1私密'),
        ),
    ]
