# Generated by Django 2.2 on 2020-08-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='role',
        ),
    ]
