# Generated by Django 2.2 on 2020-08-12 08:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='文档标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='文档内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='文档创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='文档修改时间')),
                ('type', models.IntegerField(default=0, verbose_name='是否文件夹')),
                ('status', models.IntegerField(default=1, verbose_name='文档状态')),
                ('role', models.IntegerField(default=0, verbose_name='0公开1私密')),
            ],
            options={
                'verbose_name': '文档',
            },
        ),
    ]
