# Generated by Django 2.2 on 2020-08-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200812_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='top_doc',
        ),
        migrations.AlterField(
            model_name='document',
            name='role',
            field=models.IntegerField(default=0, verbose_name='0完全公开1团队公开2团队读写3团队只读'),
        ),
    ]
