# Generated by Django 2.2 on 2020-08-13 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_auto_20200812_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_modify_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者'),
        ),
        migrations.AlterField(
            model_name='document',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create', to=settings.AUTH_USER_MODEL, verbose_name='文档创建者'),
        ),
    ]
